# Basic information
title: FINER
baseURL: https://finerreceiver.github.io/
defaultContentLanguage: ja
defaultContentLanguageInSubdir: true
enableGitInfo: false
enableEmoji: true
enableRobotsTXT: true
hasCJKLanguage: true
removePathAccents: true
permalinks:
  authors: '/author/:slug/'
  categories: '/category/:slug/'
  page: '/:slug'
  publication_types: '/publication-type/:slug/'
  tags: '/tag/:slug/'

# Dependencies
module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-netlify-cms
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-netlify
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5

markup:
  _merge: deep
security:
  _merge: deep
sitemap:
  _merge: deep
