main:
  - name: News
    url: post
    weight: 10
  - name: Science
    url: science
    weight: 20
  - name: Receiver
    url: receiver
    weight: 30
  - name: Publication
    url: publication
    weight: 40
  - name: FAQ
    url: faq
    weight: 50
