appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: M
features:
  search:
    provider: wowchemy
header:
  navbar:
    enable: true
    align: left
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true
footer:
  copyright:
    notice: '© {year} FINER team. Licensed under {license}'
    license:
      enable: true
      allow_derivatives: true
      share_alike: false
      allow_commercial: true
marketing:
  seo:
    site_type: ResearchOrganization
    org_name: 'LMT-FINER: Far-Infrared Nebular Emission Receiver for Large Millimeter Telescope'
    description: 'Project website of LMT-FINER'

