name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  job:
    name: GitHub Pages
    runs-on: ubuntu-latest
    container: klakegg/hugo:ext-ubuntu
    steps:
      - uses: actions/checkout@v3
      - run: |
          hugo --minify
          cp ./assets/google64f9f7d71c0134cc.html ./public
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
