name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.3'
          extended: true
      - run: hugo --minify
